sonar.projectKey=react-poc-app
sonar.projectName=React POC Application
sonar.projectVersion=1.0

# SonarQube server URL
sonar.host.url=http://localhost:9000

# Authentication token (create it in SonarQube UI > My Account > Security)
sonar.login=squ_e76e8d14c5ba5b3b982bdd23631cabe45d08473e

# Where your source code lives
sonar.sources=src

# Optional exclusions
sonar.exclusions=**/*.test.js,**/node_modules/**

# Encoding
sonar.sourceEncoding=UTF-8
